# Site settings
title: Little Earth Solutions
description: Delphi development tools and libraries
baseurl: "" # the subpath of your site, e.g. /blog

remote_theme: pages-themes/time-machine@v0.2.0

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  products:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Products
    url: /products/
  - title: Links
    url: /links/
  - title: About
    url: /about/

# Social links
social:
  - name: GitHub
    url: https://github.com/littleearth
  - name: Website
    url: https://littleearthsolutions.net

# Author
author:
  name: Little Earth Solutions
  email: support@littleearthsolutions.net
  description: Delphi development tools and libraries
  url: https://littleearthsolutions.net
