# Site settings
title: Little Earth Solutions
description: Open source software projects developed in our ever decreasing free time.
baseurl: "" # the subpath of your site, e.g. /blog
show_downloads: false

remote_theme: pages-themes/modernist@v0.2.0

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Social links
social:
  - name: GitHub
    url: https://github.com/littleearth
  - name: Website
    url: https://littleearthsolutions.net

# Author
author:
  name: Little Earth Solutions
  email: support@littleearthsolutions.net
  description: Open source software projects developed in our ever decreasing free time.
  url: https://littleearthsolutions.net
