# Site settings
title: Little Earth Solutions
description: Delphi development tools and libraries
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.littleearthsolutions.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-chirpy

# Collections
collections:
  products:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Products
    url: /products/
  - title: Links
    url: /links/
  - title: About
    url: /about/

# Social links
social:
  - name: GitHub
    url: https://github.com/littleearth
  - name: Website
    url: https://littleearthsolutions.net

# Author
author:
  name: Little Earth Solutions
  email: support@littleearthsolutions.net
  description: Delphi development tools and libraries
  url: https://littleearthsolutions.net

# Chirpy theme settings
avatar: /assets/littleearthsolutions-text.png
timezone: UTC
lang: en

# Chirpy theme features
theme_mode:
  light: true
  dark: true
  auto: true

# Social links for Chirpy
social:
  - name: GitHub
    url: https://github.com/littleearth
  - name: Website
    url: https://littleearthsolutions.net

# Chirpy theme appearance
tabs:
  home: home
  archive: archive
  categories: categories
  tags: tags
  collections: collections
  about: about

# Chirpy theme layout
layout:
  type: home
  profile_panel:
    enabled: true
    avatar: /assets/littleearthsolutions-text.png
    title: Little Earth Solutions
    subtitle: Delphi Development Tools & Libraries
    social_links:
      - name: GitHub
        url: https://github.com/littleearth
      - name: Website
        url: https://littleearthsolutions.net
